//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1mple_SchoolManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_Student
    {
        public System.Guid StudentID { get; set; }
        public string StudentName { get; set; }
        public bool StudentSex { get; set; }
        public string StudentIDcard { get; set; }
        public System.DateTime StudentBirth { get; set; }
        public int StudentNum { get; set; }
        public string StudentNation { get; set; }
        public string StudentContacts { get; set; }
        public string ContactsPhone { get; set; }
        public string StudentEmail { get; set; }
        public string EducationalSystem { get; set; }
        public string Education { get; set; }
        public bool StudentStatus { get; set; }
        public bool DayReading { get; set; }
        public string HomeAddress { get; set; }
        public string StudentPhotoUrl { get; set; }
        public string EmergencyContact { get; set; }
        public string EmergencyPhone { get; set; }
        public bool IsDelete { get; set; }
        public string Remark { get; set; }
    }
}
