//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1mple_SchoolManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_Location
    {
        public System.Guid LocationID { get; set; }
        public string Locus { get; set; }
        public System.DateTime Time { get; set; }
        public bool IsDelete { get; set; }
    }
}
