//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1mple_SchoolManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_Parent
    {
        public System.Guid ParentID { get; set; }
        public string ParentName { get; set; }
        public bool ParentSex { get; set; }
        public string ParentIDcard { get; set; }
        public System.DateTime ParentBirth { get; set; }
        public string ParentPhone { get; set; }
        public string HomeAddress { get; set; }
        public string ParentEmail { get; set; }
        public string ParentPhotoUrl { get; set; }
        public bool IsDelete { get; set; }
    }
}
