//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1mple_SchoolManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_Leave
    {
        public System.Guid LeaveID { get; set; }
        public string LeaveStuName { get; set; }
        public string LeaveStuNum { get; set; }
        public string LeaveStuDepartment { get; set; }
        public string LeaveStuGrade { get; set; }
        public string LeaveStuClass { get; set; }
        public string LeaveStuReasons { get; set; }
        public string Teacher { get; set; }
        public string TeacherNum { get; set; }
        public bool IsDelete { get; set; }
    }
}
