//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1mple_SchoolManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_C_S_C
    {
        public int ID { get; set; }
        public int CurriculumID { get; set; }
        public int ScheduleID { get; set; }
        public System.Guid ClassID { get; set; }
        public bool IsDelete { get; set; }
    }
}
