//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1mple_SchoolManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_C_S_C
    {
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Curriculum1 { get; set; }
        public string Curriculum2 { get; set; }
        public string Curriculum3 { get; set; }
        public string Curriculum4 { get; set; }
        public string Curriculum5 { get; set; }
        public string Curriculum6 { get; set; }
        public string Curriculum7 { get; set; }
        public bool IsDelete { get; set; }
    }
}
