//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1mple_SchoolManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_S_T_C
    {
        public string StudentName { get; set; }
        public int StudentNum { get; set; }
        public string ClassName { get; set; }
        public string Department { get; set; }
        public string TeacherName { get; set; }
        public int TeacherNum { get; set; }
        public bool IsDelete { get; set; }
    }
}
