//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1mple_SchoolManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_T_C_N
    {
        public string Expr1 { get; set; }
        public string TeacherName { get; set; }
        public bool TeacherSex { get; set; }
        public string TeacherIDcard { get; set; }
        public System.DateTime TeacherBirth { get; set; }
        public int TeacherNum { get; set; }
        public string TeacherPhone { get; set; }
        public string TeacherEmail { get; set; }
        public string HomeAddress { get; set; }
        public string TeacherPhotoUrl { get; set; }
        public string TeacherType { get; set; }
        public bool IsDelete { get; set; }
        public string Remark { get; set; }
        public string Expr2 { get; set; }
        public string NationName { get; set; }
        public string Expr3 { get; set; }
        public string Department { get; set; }
        public string Professional { get; set; }
        public string Grade { get; set; }
        public string ClassName { get; set; }
        public bool Expr4 { get; set; }
    }
}
